// <auto-generated />
namespace Cafe.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class adddatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "202004061214210_adddatabase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
